package com.company.kanban.service;
import com.company.kanban.dto.*; import com.company.kanban.entity.*; import com.company.kanban.repository.RawMaterialArrivalRepository;
import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException; import org.springframework.beans.factory.annotation.Autowired;
import java.time.*; import java.util.List;
@Service public class RawMaterialArrivalService {
    private static final ZoneId ZONE=ZoneId.of("Asia/Kuala_Lumpur"); private final RawMaterialArrivalRepository repository; private final AuthorizationService authorizationService; private final RawMaterialNotificationService notificationService; private final Clock clock;
    @Autowired public RawMaterialArrivalService(RawMaterialArrivalRepository repository, AuthorizationService authorizationService, RawMaterialNotificationService notificationService){this(repository,authorizationService,notificationService,Clock.system(ZONE));}
    RawMaterialArrivalService(RawMaterialArrivalRepository repository, AuthorizationService authorizationService, Clock clock){this(repository,authorizationService,null,clock);}
    RawMaterialArrivalService(RawMaterialArrivalRepository repository, AuthorizationService authorizationService, RawMaterialNotificationService notificationService, Clock clock){this.repository=repository;this.authorizationService=authorizationService;this.notificationService=notificationService;this.clock=clock;}
    private LocalDate today(){return LocalDate.now(clock.withZone(ZONE));}
    @Transactional(readOnly=true) public List<RawMaterialArrivalResponse> getItems(int year,int month,User user){ authorizationService.requirePpcRawMaterialArrivalAccess(user); LocalDate start; try{start=LocalDate.of(year,month,1);}catch(DateTimeException e){throw bad("year and month must identify a valid calendar month");} return repository.findForMonth(start,start.withDayOfMonth(start.lengthOfMonth())).stream().map(x->RawMaterialArrivalResponse.from(x,today())).toList(); }
    @Transactional(readOnly=true) public RawMaterialArrivalResponse getOne(Long id,User user){authorizationService.requirePpcRawMaterialArrivalAccess(user);return response(find(id));}
    @Transactional public RawMaterialArrivalResponse create(RawMaterialArrivalRequest r,User user){authorizationService.requirePpcRawMaterialArrivalAccess(user); validate(r); RawMaterialArrival saved=repository.save(new RawMaterialArrival(clean(r.materialName()),clean(r.supplierName()),clean(r.poNumber()),r.quantity(),clean(r.unit()),r.expectedArrivalDate(),r.actualArrivalDate(),clean(r.remarks()),user)); if(notificationService!=null) notificationService.runCheck(); return response(saved);}
    @Transactional public RawMaterialArrivalResponse update(Long id,RawMaterialArrivalRequest r,User user){authorizationService.requirePpcRawMaterialArrivalAccess(user); validate(r); RawMaterialArrival x=find(id); x.setMaterialName(clean(r.materialName()));x.setSupplierName(clean(r.supplierName()));x.setPoNumber(clean(r.poNumber()));x.setQuantity(r.quantity());x.setUnit(clean(r.unit()));x.setExpectedArrivalDate(r.expectedArrivalDate());x.setActualArrivalDate(r.actualArrivalDate());x.setRemarks(clean(r.remarks()));RawMaterialArrival saved=repository.save(x);if(notificationService!=null) notificationService.runCheck();return response(saved);}
    @Transactional public RawMaterialArrivalResponse markArrived(Long id,LocalDate date,User user){authorizationService.requirePpcRawMaterialArrivalAccess(user);if(date==null)throw bad("Actual arrival date is required");RawMaterialArrival x=find(id);x.setActualArrivalDate(date);return response(repository.save(x));}
    @Transactional public RawMaterialArrivalResponse followUp(Long id,RawMaterialFollowUpRequest request,User user){authorizationService.requirePpcRawMaterialArrivalAccess(user);RawMaterialArrival x=find(id);x.recordFollowUp(request.status(),LocalDateTime.now(clock.withZone(ZONE)),user,clean(request.note()));return response(repository.save(x));}
    @Transactional public void delete(Long id,User user){authorizationService.requirePpcRawMaterialArrivalAccess(user);if(!repository.existsById(id))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Raw material arrival not found");repository.deleteById(id);}
    private RawMaterialArrival find(Long id){return repository.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Raw material arrival not found"));}
    private RawMaterialArrivalResponse response(RawMaterialArrival x){return RawMaterialArrivalResponse.from(x,today());}
    private void validate(RawMaterialArrivalRequest r){if(r.expectedArrivalDate()==null)throw bad("Expected arrival date is required");if(r.materialName()==null||r.materialName().isBlank())throw bad("Material name is required");if(r.supplierName()==null||r.supplierName().isBlank())throw bad("Supplier is required");}
    private String clean(String v){return v==null||v.isBlank()?null:v.trim();} private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}
}
