package com.company.kanban.entity;

public enum NotificationType {
    TASK_CREATED,
    TASK_ASSIGNED,
    TASK_UPDATED,
    TASK_REASSIGNED,
    TASK_DUE_TOMORROW,
    TASK_DUE_TODAY,
    TASK_OVERDUE,
    TASK_REVIEW_SUBMITTED,
    TASK_REVIEW_RETURNED,
    TASK_APPROVED,
    PROJECT_CREATED,
    DAILY_REPORT_SUBMITTED,
    RAW_MATERIAL_ARRIVING_TOMORROW,
    RAW_MATERIAL_DUE_TODAY,
    RAW_MATERIAL_DELAYED,
    RAW_MATERIAL_FOLLOW_UP_DUE,
    MONTHLY_REPORT_3_DAY_REMINDER,
    MONTHLY_REPORT_MONTH_END,
    MONTHLY_REPORT_OVERDUE
}
