package com.company.kanban.entity;

public enum NotificationType {
    TASK_CREATED,
    TASK_ASSIGNED,
    TASK_UPDATED,
    TASK_REASSIGNED,
    TASK_REVIEW_SUBMITTED,
    TASK_REVIEW_RETURNED,
    TASK_APPROVED,
    PROJECT_CREATED,
    DAILY_REPORT_SUBMITTED,
    RAW_MATERIAL_ARRIVING_TOMORROW,
    RAW_MATERIAL_DUE_TODAY,
    RAW_MATERIAL_DELAYED,
    RAW_MATERIAL_FOLLOW_UP_DUE
}
