import { useEffect, useState } from "react";
import { apiFetch } from "../api/apiFetch";

const zone = "Asia/Kuala_Lumpur";
const localDate = (d) => new Intl.DateTimeFormat("en-CA", { timeZone: zone }).format(d);
function CompletedCheckpointDetails({ task }) {
  const [open, setOpen] = useState(false); const [items, setItems] = useState([]); const [loading, setLoading] = useState(false);
  if (task.departmentName?.toUpperCase() !== "RDD") return null;
  async function toggle() { const next = !open; setOpen(next); if (next && !items.length) { setLoading(true); const response = await apiFetch(`/api/tasks/${task.id}/checkpoints`); if (response.ok) setItems(await response.json()); setLoading(false); } }
  return <div className="completed-checkpoints"><button type="button" className="secondary-button" onClick={toggle}>{open ? "Hide checkpoints" : "Show checkpoints"}</button>{open && (loading ? <small>Loading checkpoints...</small> : !items.length ? <small>No checkpoints.</small> : <ul>{items.map((item) => <li key={item.id}>{item.status === "COMPLETED" ? "✓" : "○"} {item.title}{item.completedAt ? ` · Completed ${item.completedAt.slice(0, 10)}` : ""}</li>)}</ul>)}</div>;
}
function CompletedTasksPage() {
  const [range, setRange] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState("");
  const [result, setResult] = useState(null); const [page, setPage] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { const params = new URLSearchParams({ page, size: 20 }); if (range === "custom") { if (from) params.set("from", from); if (to) params.set("to", to); } else if (range) { const today = localDate(new Date()); params.set("to", today); if (range === "month") params.set("from", `${today.slice(0, 8)}01`); else { const d = new Date(`${today}T00:00:00+08:00`); d.setUTCDate(d.getUTCDate() - (range === "week" ? 7 : 30)); params.set("from", localDate(d)); } } let cancelled = false; setLoading(true); apiFetch(`/api/tasks/completed?${params}`).then(async (r) => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.json(); }).then((data) => { if (!cancelled) { setResult(data); setError(""); setLoading(false); } }).catch((loadError) => { if (!cancelled) { setError(`Unable to load completed tasks (${loadError.message}).`); setLoading(false); } }); return () => { cancelled = true; }; }, [range, from, to, page]);
  const changeRange = (value) => { setRange(value); setPage(0); };
  return <><div className="personal-kanban-heading"><div><h1>Completed Tasks</h1><p>All completed work, including tasks older than the active-board window.</p></div></div><div className="board-toolbar"><div className="toolbar-field"><label htmlFor="completed-range">Date range</label><select id="completed-range" value={range} onChange={(e) => changeRange(e.target.value)}><option value="">All completed</option><option value="week">This Week</option><option value="month">This Month</option><option value="last-month">Last Month</option><option value="custom">Custom Date Range</option></select></div>{range === "custom" && <><div className="toolbar-field"><label htmlFor="completed-from">From</label><input id="completed-from" type="date" value={from} onChange={(e) => { setFrom(e.target.value); setPage(0); }} /></div><div className="toolbar-field"><label htmlFor="completed-to">To</label><input id="completed-to" type="date" value={to} onChange={(e) => { setTo(e.target.value); setPage(0); }} /></div></>}</div>{error && <p className="form-error" role="alert">{error}</p>}{loading ? <div className="empty-state"><p>Loading completed tasks...</p></div> : !result?.content?.length ? <div className="empty-state"><p>No completed tasks found.</p></div> : <><div className="task-list completed-task-list">{result.content.map((task) => <article className={`task-card priority-card-${String(task.priority || "MEDIUM").toLowerCase()}`} key={task.id}><h3 title={task.title}>{task.title}</h3><small className="task-board-name">{task.generalTask ? `General Task · ${task.departmentName || ""}` : task.boardName}</small><div className={`task-priority-accent priority-${String(task.priority || "MEDIUM").toLowerCase()}`} title={`Priority: ${task.priority || "MEDIUM"}`} aria-label={`Priority: ${task.priority || "MEDIUM"}`} />{task.workload != null && <small className="task-workload">Workload {task.workload}</small>}<div className="task-card-footer"><span>{task.assigneeName || "Unassigned"}</span>{task.completedAt && <span>{new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", timeZone: zone }).format(new Date(task.completedAt))}</span>}</div><CompletedCheckpointDetails task={task} /></article>)}</div><div className="history-pagination"><button type="button" disabled={result.first} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page + 1} of {result.totalPages || 1}</span><button type="button" disabled={result.last} onClick={() => setPage(page + 1)}>Next</button></div></>}</>;
}
export default CompletedTasksPage;
