import { useCallback, useEffect, useState } from "react";
import { apiFetch } from "../api/apiFetch";
const bytes=n=>{if(n<1024)return `${n} B`;if(n<1048576)return `${(n/1024).toFixed(1)} KB`;return `${(n/1048576).toFixed(1)} MB`;};
async function problem(r){const d=await r.json().catch(()=>({}));return d.detail||d.message||`Request failed (${r.status})`;}
export default function DataManagementPage(){const [backups,setBackups]=useState([]),[archives,setArchives]=useState([]),[canOpenFolder,setCanOpenFolder]=useState(false),[policy,setPolicy]=useState(null),[tab,setTab]=useState('backups'),[busy,setBusy]=useState(''),[message,setMessage]=useState('');
 const load=useCallback(async()=>{try{const [b,a,s,l]=await Promise.all([apiFetch('/api/admin/data-management/backups'),apiFetch('/api/admin/data-management/archives'),apiFetch('/api/admin/data-management/status'),apiFetch('/api/admin/data-management/location')]);if(!b.ok)throw new Error(await problem(b));setBackups(await b.json());if(a.ok)setArchives(await a.json());if(l.ok){const location=await l.json();setCanOpenFolder(location.canOpenFolder);setPolicy(location);}if(s.ok){const status=await s.json();if(status.status!=='IDLE')setMessage(status.message);}}catch(e){setMessage(e.message);}},[]);
 // Loading on mount intentionally owns the page's initial request state.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{load();},[load]);
 async function create(){setBusy('Creating backup…');setMessage('');try{const r=await apiFetch('/api/admin/data-management/backups',{method:'POST'});if(!r.ok)throw new Error(await problem(r));setMessage('Backup completed.');await load();}catch(e){setMessage(e.message);}finally{setBusy('');}}
 async function download(b){setBusy(`Exporting ${b.filename}…`);try{const r=await apiFetch(`/api/admin/data-management/backups/${encodeURIComponent(b.id)}/download`,{headers:{}});if(!r.ok)throw new Error(await problem(r));const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=b.filename;a.click();URL.revokeObjectURL(url);}catch(e){setMessage(e.message);}finally{setBusy('');}}
 async function remove(b){if(!window.confirm('Delete this backup permanently?'))return;try{const r=await apiFetch(`/api/admin/data-management/backups/${encodeURIComponent(b.id)}`,{method:'DELETE'});if(!r.ok)throw new Error(await problem(r));setMessage('Backup deleted permanently.');await load();}catch(e){setMessage(e.message);}}
 async function restore(b){if(!window.confirm('Restore this backup?\n\nThe current FlowOps database will be replaced. A safety backup will be created automatically before restore.'))return;setBusy('Creating safety backup and preparing restore…');try{const r=await apiFetch('/api/admin/data-management/restore',{method:'POST',body:JSON.stringify({backupId:b.id,confirmation:'RESTORE'})});if(!r.ok)throw new Error(await problem(r));const d=await r.json();setMessage(d.message);}catch(e){setMessage(e.message);}finally{setBusy('');}}
 async function openFolder(){try{const r=await apiFetch('/api/admin/data-management/open-folder',{method:'POST'});if(!r.ok)throw new Error(await problem(r));setMessage('Backup folder opened on the server.');}catch(e){setMessage(e.message);}}
 return <section className="admin-page"><header className="admin-page-heading"><div><p className="eyebrow">Settings · Data Management</p><h1>Backups &amp; Archives</h1><p>Create, export, and safely restore PostgreSQL backups.</p></div><div className="report-actions">{canOpenFolder&&<button className="secondary-button" onClick={openFolder}>Open Backup Folder</button>}<button className="primary-button" onClick={create} disabled={!!busy}>Create Backup Now</button></div></header>{(busy||message)&&<div className="admin-message">{busy||message}</div>}{policy&&<div className="admin-message">Retention: completed tasks visible {policy.completedTaskVisibleDays} days · notifications {policy.notificationRetentionDays} days · backups {policy.backupPolicy} · directory <code>{policy.backupDirectory}</code></div>}
 <div className="admin-tabs"><button className={tab==='backups'?'is-active':''} onClick={()=>setTab('backups')}>Backups</button><button className={tab==='archives'?'is-active':''} onClick={()=>setTab('archives')}>Archived Databases</button></div>
 {tab==='backups'?<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Filename</th><th>Created</th><th>Size</th><th>Type</th><th>Reason</th><th>Status</th><th>Actions</th></tr></thead><tbody>{backups.length?backups.map(b=><tr key={b.id}><td><strong>{b.filename}</strong></td><td>{new Date(b.createdAt).toLocaleString()}</td><td>{bytes(b.sizeBytes)}</td><td>{b.backupType.replaceAll('_',' ')}</td><td>{b.reason||'—'}</td><td><span className="status-pill active">{b.status}</span></td><td><div className="row-actions"><button onClick={()=>download(b)}>Download</button><button onClick={()=>restore(b)}>Restore</button><button className="danger-link" onClick={()=>remove(b)}>Delete</button></div></td></tr>):<tr><td colSpan="7">No backups found in the configured directory.</td></tr>}</tbody></table></div>:
 <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Archived database</th><th>Archived</th><th>Reason</th><th>Matching backup</th><th>Status</th></tr></thead><tbody>{archives.length?archives.map(a=><tr key={a.databaseName}><td><strong>{a.databaseName}</strong></td><td>{a.archivedAt?new Date(a.archivedAt).toLocaleString():'Unknown'}</td><td>{a.reason}</td><td>{a.matchingBackup||'—'}</td><td><span className="status-pill pending_activation">READ ONLY</span></td></tr>):<tr><td colSpan="5">No archived databases detected.</td></tr>}</tbody></table></div>}</section>;
}
