import { useCallback, useEffect, useMemo, useState } from "react";
import { apiFetch } from "../api/apiFetch";

const tabs=[['ALL','All'],['ACTIVE','Active'],['DISABLED','Disabled']];
const emptyForm={name:"",email:"",password:"",confirmPassword:"",departmentId:"",role:"STAFF",status:"ACTIVE"};
async function errorMessage(response){const data=await response.json().catch(()=>({}));return data.detail||data.message||`Request failed (${response.status})`;}
export default function UserManagementPage({departments,onDepartmentCreated}){
  const [users,setUsers]=useState([]),[tab,setTab]=useState('ALL'),[search,setSearch]=useState(''),[loading,setLoading]=useState(true);
  const [editing,setEditing]=useState(null),[form,setForm]=useState(emptyForm),[message,setMessage]=useState(''),[saving,setSaving]=useState(false);
  const [passwordUser,setPasswordUser]=useState(null),[passwordForm,setPasswordForm]=useState({password:"",confirmPassword:""}),[passwordSaving,setPasswordSaving]=useState(false);
  const [addingDepartment,setAddingDepartment]=useState(false),[departmentName,setDepartmentName]=useState(''),[departmentSaving,setDepartmentSaving]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{const r=await apiFetch('/api/admin/users');if(!r.ok)throw new Error(await errorMessage(r));setUsers(await r.json());}catch(e){setMessage(e.message);}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  const filtered=useMemo(()=>users.filter(u=>(tab==='ALL'||u.status===tab)&&(!search||`${u.name} ${u.email}`.toLowerCase().includes(search.toLowerCase()))),[users,tab,search]);
  function add(){setEditing('new');setForm({...emptyForm,departmentId:String(departments[0]?.id||'')});setMessage('');}
  function edit(user){setEditing(user);setForm({name:user.name,email:user.email,password:"",confirmPassword:"",departmentId:String(user.departmentId),role:user.role,status:user.status});setMessage('');}
  async function save(event){event.preventDefault();setSaving(true);setMessage('');try{const isNew=editing==='new';if(isNew&&form.password!==form.confirmPassword)throw new Error('The passwords do not match.');const payload={...form,departmentId:Number(form.departmentId)};delete payload.confirmPassword;if(!isNew){delete payload.email;delete payload.password;}
    const r=await apiFetch(isNew?'/api/admin/users':`/api/admin/users/${editing.id}`,{method:isNew?'POST':'PUT',body:JSON.stringify(payload)});if(!r.ok)throw new Error(await errorMessage(r));const saved=await r.json();
    if(isNew)setMessage(`User created. ${saved.name} can sign in now.`);
    else setMessage('User updated.');setEditing(null);await load();}catch(e){setMessage(e.message);}finally{setSaving(false);}}
  async function action(user,kind){if(kind==='disable'&&!window.confirm(`Disable ${user.name}'s account?`))return;setMessage('');try{const r=await apiFetch(`/api/admin/users/${user.id}/${kind}`,{method:'POST'});if(!r.ok)throw new Error(await errorMessage(r));setMessage(kind==='disable'?'Account disabled.':'Account reactivated.');await load();}catch(e){setMessage(e.message);}}
  async function deleteUser(user){if(!window.confirm(`Permanently delete ${user.name}? This is only allowed when the disabled account has no task or report history.`))return;setMessage('');try{const r=await apiFetch(`/api/admin/users/${user.id}`,{method:'DELETE'});if(!r.ok)throw new Error(await errorMessage(r));setMessage(`${user.name} was permanently deleted.`);await load();}catch(e){setMessage(e.message);}}
  async function saveDepartment(event){event.preventDefault();setDepartmentSaving(true);setMessage('');try{const r=await apiFetch('/api/departments',{method:'POST',body:JSON.stringify({name:departmentName})});if(!r.ok)throw new Error(await errorMessage(r));const department=await r.json();onDepartmentCreated(department);setAddingDepartment(false);setDepartmentName('');setMessage(`${department.name} department added.`);}catch(e){setMessage(e.message);}finally{setDepartmentSaving(false);}}
  function changePassword(user){setPasswordUser(user);setPasswordForm({password:"",confirmPassword:""});setMessage('');}
  async function savePassword(event){event.preventDefault();if(passwordForm.password!==passwordForm.confirmPassword){setMessage('The passwords do not match.');return;}setPasswordSaving(true);setMessage('');try{const r=await apiFetch(`/api/admin/users/${passwordUser.id}/password`,{method:'POST',body:JSON.stringify({password:passwordForm.password})});if(!r.ok)throw new Error(await errorMessage(r));setMessage(`Password updated for ${passwordUser.name}. Tell them the new password through an approved company channel.`);setPasswordUser(null);await load();}catch(e){setMessage(e.message);}finally{setPasswordSaving(false);}}
  return <section className="admin-page"><header className="admin-page-heading"><div><p className="eyebrow">Administration</p><h1>User Management</h1><p>Create company identities, departments, and manage access while preserving historical work.</p></div><div className="admin-heading-actions"><button className="secondary-button" onClick={()=>{setAddingDepartment(true);setDepartmentName('');setMessage('');}}>+ Add Department</button><button className="primary-button" onClick={add}>+ Add User</button></div></header>
    {message&&<div className={`admin-message ${/failed|cannot|invalid|exists|do not match|must be at least|not configured|not usable|unavailable/i.test(message)?'error':''}`}>{message}</div>}
    <div className="admin-controls"><div className="admin-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'is-active':''} onClick={()=>setTab(id)}>{label}</button>)}</div><input className="admin-search" type="search" placeholder="Search name, username, or email" value={search} onChange={e=>setSearch(e.target.value)}/></div>
    <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Name</th><th>Username / Email</th><th>Department</th><th>Role</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>
      {loading?<tr><td colSpan="7">Loading users…</td></tr>:filtered.length===0?<tr><td colSpan="7">No users match this view.</td></tr>:filtered.map(u=><tr key={u.id}><td><strong>{u.name}</strong></td><td>{u.email}</td><td>{u.departmentName}</td><td>{u.role}</td><td><span className={`status-pill ${u.status.toLowerCase()}`}>{u.status.replaceAll('_',' ')}</span></td><td>{new Date(u.createdAt).toLocaleDateString()}</td><td><div className="row-actions"><button onClick={()=>edit(u)}>Edit</button><button onClick={()=>changePassword(u)}>Set Password</button>{u.status==='DISABLED'?<><button onClick={()=>action(u,'reactivate')}>Reactivate</button><button className="danger-link" onClick={()=>deleteUser(u)}>Delete</button></>:<button className="danger-link" onClick={()=>action(u,'disable')}>Disable</button>}</div></td></tr>)}</tbody></table></div>
    {editing&&<div className="modal-backdrop"><div className="modal-card admin-modal"><div className="modal-header"><div><h2>{editing==='new'?'Add User':'Edit User'}</h2><p>{editing==='new'?'Set the sign-in details now. No activation link is needed.':'Changes preserve all historical work.'}</p></div><button className="modal-close-button" onClick={()=>setEditing(null)}>×</button></div><form onSubmit={save} className="admin-form">
      <label>Full Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label>{editing==='new'&&<><label>Username or Email<input type="text" autoComplete="username" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><small className="form-help">A short username such as afiq or a company email address both work.</small></label><label>Password<input type="password" autoComplete="new-password" minLength="8" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/></label><label>Confirm Password<input type="password" autoComplete="new-password" minLength="8" value={form.confirmPassword} onChange={e=>setForm({...form,confirmPassword:e.target.value})} required/></label></>}
      <label>Department<select value={form.departmentId} onChange={e=>setForm({...form,departmentId:e.target.value})} required>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>
      <label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option>STAFF</option><option>MANAGER</option><option>ADMIN</option></select></label>
      {editing!=='new'&&<label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="PENDING_ACTIVATION">PENDING ACTIVATION</option>{editing.status!=='PENDING_ACTIVATION'&&<option>ACTIVE</option>}<option>DISABLED</option></select></label>}
      <div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setEditing(null)}>Cancel</button><button className="primary-button" disabled={saving}>{saving?'Saving…':'Save User'}</button></div></form></div></div>}
    {passwordUser&&<div className="modal-backdrop"><div className="modal-card admin-modal"><div className="modal-header"><div><h2>Set Password</h2><p>Replace the sign-in password for {passwordUser.name}. The existing password cannot be displayed.</p></div><button className="modal-close-button" onClick={()=>setPasswordUser(null)}>×</button></div><form onSubmit={savePassword} className="admin-form">
      <label>New Password<input type="password" autoComplete="new-password" minLength="8" value={passwordForm.password} onChange={e=>setPasswordForm({...passwordForm,password:e.target.value})} autoFocus required/></label>
      <label>Confirm New Password<input type="password" autoComplete="new-password" minLength="8" value={passwordForm.confirmPassword} onChange={e=>setPasswordForm({...passwordForm,confirmPassword:e.target.value})} required/></label>
      <div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setPasswordUser(null)}>Cancel</button><button className="primary-button" disabled={passwordSaving}>{passwordSaving?'Updating…':'Update Password'}</button></div></form></div></div>}
    {addingDepartment&&<div className="modal-backdrop"><div className="modal-card admin-modal"><div className="modal-header"><div><h2>Add Department</h2><p>The department becomes available immediately when creating or editing users.</p></div><button className="modal-close-button" onClick={()=>setAddingDepartment(false)}>×</button></div><form onSubmit={saveDepartment} className="admin-form">
      <label>Department Name<input value={departmentName} onChange={e=>setDepartmentName(e.target.value)} maxLength="100" autoFocus required/></label>
      <div className="modal-actions"><button type="button" className="secondary-button" onClick={()=>setAddingDepartment(false)}>Cancel</button><button className="primary-button" disabled={departmentSaving}>{departmentSaving?'Adding…':'Add Department'}</button></div></form></div></div>}
  </section>;
}
